//
//  offsets.h
//  lara
//
//  Created by ruter on 04.04.26.
//

#ifndef offsets_h
#define offsets_h

#import <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/types.h>
#import <Foundation/Foundation.h>

#ifdef __cplusplus
extern "C" {
#endif

// Infern0 also ships its original kernel engine, whose public offset names
// match Lara's. Keep Lara's complete offset set in a separate namespace so
// both engines can coexist in one executable without duplicate symbols.
#define off_inpcb_inp_list_le_next lara_off_inpcb_inp_list_le_next
#define gIsPACSupported lara_gIsPACSupported
#define gIsA18Above lara_gIsA18Above
#define off_inpcb_inp_pcbinfo lara_off_inpcb_inp_pcbinfo
#define off_inpcb_inp_socket lara_off_inpcb_inp_socket
#define off_inpcbinfo_ipi_zone lara_off_inpcbinfo_ipi_zone
#define off_inpcb_inp_depend6_inp6_icmp6filt lara_off_inpcb_inp_depend6_inp6_icmp6filt
#define off_inpcb_inp_depend6_inp6_chksum lara_off_inpcb_inp_depend6_inp6_chksum
#define off_socket_so_usecount lara_off_socket_so_usecount
#define off_socket_so_proto lara_off_socket_so_proto
#define off_socket_so_background_thread lara_off_socket_so_background_thread
#define off_protosw_pr_input lara_off_protosw_pr_input
#define off_kalloc_type_view_kt_zv_zv_name lara_off_kalloc_type_view_kt_zv_zv_name
#define off_thread_t_tro lara_off_thread_t_tro
#define off_thread_ro_tro_proc lara_off_thread_ro_tro_proc
#define off_thread_ro_tro_task lara_off_thread_ro_tro_task
#define off_thread_machine_upcb lara_off_thread_machine_upcb
#define off_thread_machine_contextdata lara_off_thread_machine_contextdata
#define off_thread_ctid lara_off_thread_ctid
#define off_thread_options lara_off_thread_options
#define off_thread_mutex_lck_mtx_data lara_off_thread_mutex_lck_mtx_data
#define off_thread_machine_kstackptr lara_off_thread_machine_kstackptr
#define off_thread_guard_exc_info_code lara_off_thread_guard_exc_info_code
#define off_thread_mach_exc_info_code lara_off_thread_mach_exc_info_code
#define off_thread_mach_exc_info_os_reason lara_off_thread_mach_exc_info_os_reason
#define off_thread_mach_exc_info_exception_type lara_off_thread_mach_exc_info_exception_type
#define off_thread_ast lara_off_thread_ast
#define off_thread_task_threads_next lara_off_thread_task_threads_next
#define off_thread_machine_jop_pid lara_off_thread_machine_jop_pid
#define off_thread_machine_rop_pid lara_off_thread_machine_rop_pid
#define off_proc_p_list_le_next lara_off_proc_p_list_le_next
#define off_proc_p_list_le_prev lara_off_proc_p_list_le_prev
#define off_proc_p_proc_ro lara_off_proc_p_proc_ro
#define off_proc_p_pid lara_off_proc_p_pid
#define off_proc_p_fd lara_off_proc_p_fd
#define off_proc_p_flag lara_off_proc_p_flag
#define off_proc_p_textvp lara_off_proc_p_textvp
#define off_proc_p_name lara_off_proc_p_name
#define off_proc_ro_pr_task lara_off_proc_ro_pr_task
#define off_proc_ro_p_ucred lara_off_proc_ro_p_ucred
#define off_ucred_cr_label lara_off_ucred_cr_label
#define off_task_itk_space lara_off_task_itk_space
#define off_task_threads_next lara_off_task_threads_next
#define off_task_task_exc_guard lara_off_task_task_exc_guard
#define off_task_map lara_off_task_map
#define off_filedesc_fd_ofiles lara_off_filedesc_fd_ofiles
#define off_filedesc_fd_cdir lara_off_filedesc_fd_cdir
#define off_fileproc_fp_glob lara_off_fileproc_fp_glob
#define off_fileglob_fg_data lara_off_fileglob_fg_data
#define off_fileglob_fg_flag lara_off_fileglob_fg_flag
#define off_vnode_v_ncchildren_tqh_first lara_off_vnode_v_ncchildren_tqh_first
#define off_vnode_v_nclinks_lh_first lara_off_vnode_v_nclinks_lh_first
#define off_vnode_v_parent lara_off_vnode_v_parent
#define off_vnode_v_data lara_off_vnode_v_data
#define off_vnode_v_name lara_off_vnode_v_name
#define off_vnode_v_usecount lara_off_vnode_v_usecount
#define off_vnode_v_iocount lara_off_vnode_v_iocount
#define off_vnode_v_writecount lara_off_vnode_v_writecount
#define off_vnode_v_flag lara_off_vnode_v_flag
#define off_vnode_v_mount lara_off_vnode_v_mount
#define off_mount_mnt_flag lara_off_mount_mnt_flag
#define off_namecache_nc_vp lara_off_namecache_nc_vp
#define off_namecache_nc_child_tqe_next lara_off_namecache_nc_child_tqe_next
#define off_arm_saved_state64_lr lara_off_arm_saved_state64_lr
#define off_arm_saved_state64_pc lara_off_arm_saved_state64_pc
#define off_arm_saved_state_uss_ss_64 lara_off_arm_saved_state_uss_ss_64
#define off_ipc_space_is_table lara_off_ipc_space_is_table
#define off_ipc_entry_ie_object lara_off_ipc_entry_ie_object
#define off_ipc_port_ip_kobject lara_off_ipc_port_ip_kobject
#define off_arm_kernel_saved_state_sp lara_off_arm_kernel_saved_state_sp
#define off_vm_map_hdr lara_off_vm_map_hdr
#define off_vm_map_header_nentries lara_off_vm_map_header_nentries
#define off_vm_map_entry_links_next lara_off_vm_map_entry_links_next
#define off_vm_map_entry_vme_object_or_delta lara_off_vm_map_entry_vme_object_or_delta
#define off_vm_map_entry_vme_alias lara_off_vm_map_entry_vme_alias
#define off_vm_map_header_links_next lara_off_vm_map_header_links_next
#define off_vm_object_vo_un1_vou_size lara_off_vm_object_vo_un1_vou_size
#define off_vm_object_ref_count lara_off_vm_object_ref_count
#define off_vm_named_entry_backing_copy lara_off_vm_named_entry_backing_copy
#define off_vm_named_entry_size lara_off_vm_named_entry_size
#define off_label_l_perpolicy_amfi lara_off_label_l_perpolicy_amfi
#define off_label_l_perpolicy_sandbox lara_off_label_l_perpolicy_sandbox
#define sizeof_ipc_entry lara_sizeof_ipc_entry
#define smr_base lara_smr_base
#define t1sz_boot lara_t1sz_boot
#define VM_MIN_KERNEL_ADDRESS lara_VM_MIN_KERNEL_ADDRESS
#define VM_MAX_KERNEL_ADDRESS lara_VM_MAX_KERNEL_ADDRESS
#define pac_mask lara_pac_mask
#define savealloffsets lara_savealloffsets
#define setoffsetvalue lara_setoffsetvalue
#define verifykernoffsets lara_verifykernoffsets
#define emergencyfixfunctiontobereplacedlateronquestionmark lara_emergencyfixfunctiontobereplacedlateronquestionmark
#define dlkcache lara_dlkcache
#define getrootvnode lara_getrootvnode
#define getmacprocenforceoff lara_getmacprocenforceoff
#define getkerncache lara_getkerncache
#define clearkerncachedata lara_clearkerncachedata
#define is_pac_supported lara_is_pac_supported
#define get_hw_cpufamily lara_get_hw_cpufamily

extern uint32_t off_inpcb_inp_list_le_next;
extern uint32_t off_inpcb_inp_pcbinfo;
extern uint32_t off_inpcb_inp_socket;
extern uint32_t off_inpcbinfo_ipi_zone;
extern uint32_t off_inpcb_inp_depend6_inp6_icmp6filt;
extern uint32_t off_inpcb_inp_depend6_inp6_chksum;
extern uint32_t off_socket_so_usecount;
extern uint32_t off_socket_so_proto;
extern uint32_t off_socket_so_background_thread;
extern uint32_t off_protosw_pr_input;
extern uint32_t off_kalloc_type_view_kt_zv_zv_name;
extern uint32_t off_thread_t_tro;
extern uint32_t off_thread_ro_tro_proc;
extern uint32_t off_thread_ro_tro_task;
extern uint32_t off_thread_machine_upcb;
extern uint32_t off_thread_machine_contextdata;
extern uint32_t off_thread_ctid;
extern uint32_t off_thread_options;
extern uint32_t off_thread_mutex_lck_mtx_data;
extern uint32_t off_thread_machine_kstackptr;
extern uint32_t off_thread_guard_exc_info_code;
extern uint32_t off_thread_mach_exc_info_code;
extern uint32_t off_thread_mach_exc_info_os_reason;
extern uint32_t off_thread_mach_exc_info_exception_type;
extern uint32_t off_thread_ast;
extern uint32_t off_thread_task_threads_next;
extern uint32_t off_thread_machine_jop_pid;
extern uint32_t off_thread_machine_rop_pid;
extern uint32_t off_proc_p_list_le_next;
extern uint32_t off_proc_p_list_le_prev;
extern uint32_t off_proc_p_proc_ro;
extern uint32_t off_proc_p_pid;
extern uint32_t off_proc_p_fd;
extern uint32_t off_proc_p_flag;
extern uint32_t off_proc_p_textvp;
extern uint32_t off_proc_p_name;
extern uint32_t off_proc_ro_pr_task;
extern uint32_t off_proc_ro_p_ucred;
extern uint32_t off_ucred_cr_label;
extern uint32_t off_task_itk_space;
extern uint32_t off_task_threads_next;
extern uint32_t off_task_task_exc_guard;
extern uint32_t off_task_map;
extern uint32_t off_filedesc_fd_ofiles;
extern uint32_t off_filedesc_fd_cdir;
extern uint32_t off_fileproc_fp_glob;
extern uint32_t off_fileglob_fg_data;
extern uint32_t off_fileglob_fg_flag;
extern uint32_t off_vnode_v_ncchildren_tqh_first;
extern uint32_t off_vnode_v_nclinks_lh_first;
extern uint32_t off_vnode_v_parent;
extern uint32_t off_vnode_v_data;
extern uint32_t off_vnode_v_name;
extern uint32_t off_vnode_v_usecount;
extern uint32_t off_vnode_v_iocount;
extern uint32_t off_vnode_v_writecount;
extern uint32_t off_vnode_v_flag;
extern uint32_t off_vnode_v_mount;
extern uint32_t off_mount_mnt_flag;
extern uint32_t off_namecache_nc_vp;
extern uint32_t off_namecache_nc_child_tqe_next;
extern uint32_t off_arm_saved_state64_lr;
extern uint32_t off_arm_saved_state64_pc;
extern uint32_t off_arm_saved_state_uss_ss_64;
extern uint32_t off_ipc_space_is_table;
extern uint32_t off_ipc_entry_ie_object;
extern uint32_t off_ipc_port_ip_kobject;
extern uint32_t off_arm_kernel_saved_state_sp;
extern uint32_t off_vm_map_hdr;
extern uint32_t off_vm_map_header_nentries;
extern uint32_t off_vm_map_entry_links_next;
extern uint32_t off_vm_map_entry_vme_object_or_delta;
extern uint32_t off_vm_map_entry_vme_alias;
extern uint32_t off_vm_map_header_links_next;
extern uint32_t off_vm_object_vo_un1_vou_size;
extern uint32_t off_vm_object_ref_count;
extern uint32_t off_vm_named_entry_backing_copy;
extern uint32_t off_vm_named_entry_size;
extern uint32_t off_label_l_perpolicy_amfi;
extern uint32_t off_label_l_perpolicy_sandbox;

extern uint32_t sizeof_ipc_entry;

extern uint64_t smr_base;
extern uint64_t t1sz_boot;
extern uint64_t VM_MIN_KERNEL_ADDRESS;
extern uint64_t VM_MAX_KERNEL_ADDRESS;

extern uint64_t pac_mask;

NSDictionary *alloffs(void);
bool setoffsetvalue(NSString *name, uint64_t value);

void savealloffsets(void);

bool verifykernoffsets(void);
bool emergencyfixfunctiontobereplacedlateronquestionmark(void);

void lara_offsets_init(void);

bool dlkcache(void);
static bool resolvekernoffsets(NSString *kcpath);
uint64_t getrootvnode(void);
uint64_t getmacprocenforceoff(void);
NSString *getkerncache(void);
void clearkerncachedata(void);
bool is_pac_supported(void);
cpu_subtype_t get_hw_cpufamily(void);

#ifdef __cplusplus
}
#endif

#endif /* offsets_h */
