#import <Foundation/Foundation.h>
#import <stdint.h>

// Link-only compatibility for UI code being removed after the retired tweak
// implementations. Returning zero/nil makes every stale operation fail closed.
__attribute__((used)) uintptr_t roundedicons_configure() { return 0; }
__attribute__((used)) uintptr_t roundedicons_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t roundedicons_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t roundedicons_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t freeplacement_configure() { return 0; }
__attribute__((used)) uintptr_t freeplacement_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t freeplacement_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t freeplacement_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_configure() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_forget_remote_state() { return 0; }

__attribute__((used)) uintptr_t alkaline_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t alkaline_configure() { return 0; }
__attribute__((used)) uintptr_t alkaline_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t alkaline_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccicons_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccicons_configure() { return 0; }
__attribute__((used)) uintptr_t betterccicons_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t betterccicons_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccxi_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccxi_configure() { return 0; }
__attribute__((used)) uintptr_t betterccxi_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t betterccxi_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_configure() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_configure() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t ccstatus_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t ccstatus_configure() { return 0; }
__attribute__((used)) uintptr_t ccstatus_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t ccstatus_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t cleancc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t cleancc_configure() { return 0; }
__attribute__((used)) uintptr_t cleancc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t cleancc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t cleanhomescreen_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t cleanhomescreen_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t cleanhomescreen_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t cleannc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t cleannc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t cleannc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t communityports_apply() { return 0; }
__attribute__((used)) uintptr_t communityports_configure() { return 0; }
__attribute__((used)) uintptr_t communityports_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t communityports_stop() { return 0; }
__attribute__((used)) uintptr_t communityports_stop_all() { return 0; }
__attribute__((used)) uintptr_t fakeclockup_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t fakeclockup_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t fakeclockup_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t fugap_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t fugap_configure() { return 0; }
__attribute__((used)) uintptr_t fugap_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t fugap_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t hapticcc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t hapticcc_configure() { return 0; }
__attribute__((used)) uintptr_t hapticcc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t hapticcc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t hidellabels_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t hidellabels_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t hidellabels_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t modulespacing_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t modulespacing_configure() { return 0; }
__attribute__((used)) uintptr_t modulespacing_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t modulespacing_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t pancake_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t pancake_configure() { return 0; }
__attribute__((used)) uintptr_t pancake_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t pancake_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t pullover_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t pullover_configure() { return 0; }
__attribute__((used)) uintptr_t pullover_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t pullover_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t realcc_apply() { return 0; }
__attribute__((used)) uintptr_t realcc_restore() { return 0; }
__attribute__((used)) uintptr_t securecc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t securecc_configure() { return 0; }
__attribute__((used)) uintptr_t securecc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t securecc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_capture_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_clear_pins_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_configure() { return 0; }
__attribute__((used)) uintptr_t snapper_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t snapper_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t sugarcane_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t sugarcane_configure() { return 0; }
__attribute__((used)) uintptr_t sugarcane_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t sugarcane_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t tweakloader_apply_at() { return 0; }
__attribute__((used)) uintptr_t tweakloader_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t tweakloader_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t tweakloader_loaded_count() { return 0; }
__attribute__((used)) uintptr_t tweakloader_name_at() { return 0; }
__attribute__((used)) uintptr_t tweakloader_register() { return 0; }
__attribute__((used)) uintptr_t tweakloader_reload_list() { return 0; }
__attribute__((used)) uintptr_t tweakloader_stop_at() { return 0; }
__attribute__((used)) uintptr_t tweakloader_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t undertime_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t undertime_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t undertime_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t velvet_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t velvet_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t velvet_has_remote_state() { return 0; }
__attribute__((used)) uintptr_t velvet_set_global_style() { return 0; }
__attribute__((used)) uintptr_t velvet_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t velvet_tick_in_session() { return 0; }
__attribute__((used)) uintptr_t zeppelinlite_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t zeppelinlite_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t zeppelinlite_stop_in_session() { return 0; }
