#import <Foundation/Foundation.h>
#import <stdint.h>

// Link-only compatibility for UI code being removed after the retired tweak
// implementations. Returning zero/nil makes every stale operation fail closed.
NSString * const RepoTweaksDidRefreshNotification = @"RepoTweaksDidRefreshNotification";
NSString * const kSnowBoardLiteThemeBuiltinIOS6 = @"builtin.ios6";

__attribute__((used)) uintptr_t roundedicons_configure() { return 0; }
__attribute__((used)) uintptr_t roundedicons_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t roundedicons_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t roundedicons_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t freeplacement_configure() { return 0; }
__attribute__((used)) uintptr_t freeplacement_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t freeplacement_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t freeplacement_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_configure() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t applibrarystudio_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t darksword_drag_coefficient_apply() { return 0; }

__attribute__((used)) uintptr_t alkaline_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t alkaline_configure() { return 0; }
__attribute__((used)) uintptr_t alkaline_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t alkaline_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t appswitchergrid_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t appswitchergrid_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t appswitchergrid_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccicons_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccicons_configure() { return 0; }
__attribute__((used)) uintptr_t betterccicons_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t betterccicons_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccxi_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t betterccxi_configure() { return 0; }
__attribute__((used)) uintptr_t betterccxi_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t betterccxi_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_configure() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t blurrybadges_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t call_recording_sound_set_disabled() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_configure() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t ccnoplatterdim_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t ccstatus_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t ccstatus_configure() { return 0; }
__attribute__((used)) uintptr_t ccstatus_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t ccstatus_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t cleancc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t cleancc_configure() { return 0; }
__attribute__((used)) uintptr_t cleancc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t cleancc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t cleanhomescreen_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t cleanhomescreen_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t cleanhomescreen_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t cleannc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t cleannc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t cleannc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t communityports_apply() { return 0; }
__attribute__((used)) uintptr_t communityports_configure() { return 0; }
__attribute__((used)) uintptr_t communityports_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t communityports_stop() { return 0; }
__attribute__((used)) uintptr_t communityports_stop_all() { return 0; }
__attribute__((used)) uintptr_t fakeclockup_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t fakeclockup_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t fakeclockup_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_attempt_unlock_in_session() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_disable_always_on_in_session() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_enable_always_on_in_session() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_probe_in_session() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_run_in_session() { return 0; }
__attribute__((used)) uintptr_t fastlockx_lite_set_always_on_active_in_session() { return 0; }
__attribute__((used)) uintptr_t fugap_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t fugap_configure() { return 0; }
__attribute__((used)) uintptr_t fugap_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t fugap_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t hapticcc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t hapticcc_configure() { return 0; }
__attribute__((used)) uintptr_t hapticcc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t hapticcc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t hide_home_bar_apply() { return 0; }
__attribute__((used)) uintptr_t hide_home_bar_restore() { return 0; }
__attribute__((used)) uintptr_t hidellabels_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t hidellabels_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t hidellabels_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_app_store_account_summary() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_clear_app_store_account() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_default_output_directory() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_display_name_for_bundle() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_download_app_store_ipa() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_has_app_store_account() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_installed_apps() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_login_app_store() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_probe_installed_app() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_resolve_app_store_input() { return 0; }
__attribute__((used)) uintptr_t ipadecryptor_start_decrypt_installed_app() { return 0; }
__attribute__((used)) uintptr_t livewp_absolute_path() { return 0; }
__attribute__((used)) uintptr_t livewp_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t livewp_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t livewp_mood_absolute_paths() { return 0; }
__attribute__((used)) uintptr_t livewp_pause_in_session() { return 0; }
__attribute__((used)) uintptr_t livewp_repair_in_session() { return 0; }
__attribute__((used)) uintptr_t livewp_resume_in_session() { return 0; }
__attribute__((used)) uintptr_t livewp_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t livewp_swap_video_in_session() { return 0; }
__attribute__((used)) uintptr_t locationsim_apply_static() { return 0; }
__attribute__((used)) uintptr_t locationsim_apply_strict_hosts() { return 0; }
__attribute__((used)) uintptr_t locationsim_stop() { return 0; }
__attribute__((used)) uintptr_t locationsim_stop_strict_hosts() { return 0; }
__attribute__((used)) uintptr_t magma_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t magma_configure() { return 0; }
__attribute__((used)) uintptr_t magma_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t magma_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t modulespacing_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t modulespacing_configure() { return 0; }
__attribute__((used)) uintptr_t modulespacing_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t modulespacing_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t nbl_traffic_counter_reset() { return 0; }
__attribute__((used)) uintptr_t nbl_traffic_counter_sample() { return 0; }
__attribute__((used)) uintptr_t nbl_traffic_counter_seed_accumulated() { return 0; }
__attribute__((used)) uintptr_t nbl_traffic_counter_value() { return 0; }
__attribute__((used)) uintptr_t nicebarlite_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t nicebarlite_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t nicebarlite_format_traffic_bytes() { return 0; }
__attribute__((used)) uintptr_t nicebarlite_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t nicebarlite_traffic_history_snapshot() { return 0; }
__attribute__((used)) uintptr_t nicebarlite_traffic_store_path() { return 0; }
__attribute__((used)) uintptr_t notificationisland_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t notificationisland_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t notificationisland_has_remote_state() { return 0; }
__attribute__((used)) uintptr_t notificationisland_show_sample_in_session() { return 0; }
__attribute__((used)) uintptr_t notificationisland_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t notificationisland_tick_in_session() { return 0; }
__attribute__((used)) uintptr_t nsbar_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t nsbar_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t nsbar_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t pancake_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t pancake_configure() { return 0; }
__attribute__((used)) uintptr_t pancake_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t pancake_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t pullover_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t pullover_configure() { return 0; }
__attribute__((used)) uintptr_t pullover_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t pullover_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t quickloader_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t quickloader_clear_repo_tweak_if_matches() { return 0; }
__attribute__((used)) uintptr_t quickloader_is_driven_by_repo_tweak() { return 0; }
__attribute__((used)) uintptr_t quickloader_is_repo_tweak_installed() { return 0; }
__attribute__((used)) uintptr_t quickloader_refresh_active_repo_tweak() { return 0; }
__attribute__((used)) uintptr_t quickloader_run_js_string() { return 0; }
__attribute__((used)) uintptr_t quickloader_save_repo_tweak() { return 0; }
__attribute__((used)) uintptr_t quickloader_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t realcc_apply() { return 0; }
__attribute__((used)) uintptr_t realcc_restore() { return 0; }
__attribute__((used)) uintptr_t repotweaks_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t repotweaks_available_update_count() { return 0; }
__attribute__((used)) uintptr_t repotweaks_builtin_repo_display_name() { return 0; }
__attribute__((used)) uintptr_t repotweaks_cancel_tweak() { return 0; }
__attribute__((used)) uintptr_t repotweaks_compare_versions() { return 0; }
__attribute__((used)) uintptr_t repotweaks_compatibility_note() { return 0; }
__attribute__((used)) uintptr_t repotweaks_download_script() { return 0; }
__attribute__((used)) uintptr_t repotweaks_download_script_sync() { return 0; }
__attribute__((used)) uintptr_t repotweaks_enabled_defaults_key() { return 0; }
__attribute__((used)) uintptr_t repotweaks_installed_version_key() { return 0; }
__attribute__((used)) uintptr_t repotweaks_is_builtin_repo() { return 0; }
__attribute__((used)) uintptr_t repotweaks_refresh_all_sources() { return 0; }
__attribute__((used)) uintptr_t repotweaks_refresh_repo() { return 0; }
__attribute__((used)) uintptr_t repotweaks_script_defaults_key() { return 0; }
__attribute__((used)) uintptr_t repotweaks_seed_default_repos() { return 0; }
__attribute__((used)) uintptr_t repotweaks_seen_timestamp() { return 0; }
__attribute__((used)) uintptr_t repotweaks_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t repotweaks_storage_key() { return 0; }
__attribute__((used)) uintptr_t repotweaks_unsupported_reason() { return 0; }
__attribute__((used)) uintptr_t repotweaks_values_defaults_key() { return 0; }
__attribute__((used)) uintptr_t securecc_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t securecc_configure() { return 0; }
__attribute__((used)) uintptr_t securecc_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t securecc_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t settings_apply_snowboardlite_from_defaults_locked() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_import_folder_theme() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_import_folder_theme_named() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_load_manifest() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_preview_images_for_theme() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_resolved_icons_path_for_theme() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_save_manifest() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_selected_builtin_ios6() { return 0; }
__attribute__((used)) uintptr_t settings_sbl_selected_theme() { return 0; }
__attribute__((used)) uintptr_t settings_snowboardlite_has_selected_theme() { return 0; }
__attribute__((used)) uintptr_t settings_snowboardlite_selected_theme_display_name() { return 0; }
__attribute__((used)) uintptr_t snapper_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_capture_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_clear_pins_in_session() { return 0; }
__attribute__((used)) uintptr_t snapper_configure() { return 0; }
__attribute__((used)) uintptr_t snapper_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t snapper_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t sugarcane_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t sugarcane_configure() { return 0; }
__attribute__((used)) uintptr_t sugarcane_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t sugarcane_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t tweakloader_apply_at() { return 0; }
__attribute__((used)) uintptr_t tweakloader_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t tweakloader_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t tweakloader_loaded_count() { return 0; }
__attribute__((used)) uintptr_t tweakloader_name_at() { return 0; }
__attribute__((used)) uintptr_t tweakloader_register() { return 0; }
__attribute__((used)) uintptr_t tweakloader_reload_list() { return 0; }
__attribute__((used)) uintptr_t tweakloader_stop_at() { return 0; }
__attribute__((used)) uintptr_t tweakloader_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t undertime_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t undertime_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t undertime_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t velvet_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t velvet_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t velvet_has_remote_state() { return 0; }
__attribute__((used)) uintptr_t velvet_set_global_style() { return 0; }
__attribute__((used)) uintptr_t velvet_stop_in_session() { return 0; }
__attribute__((used)) uintptr_t velvet_tick_in_session() { return 0; }
__attribute__((used)) uintptr_t zeppelinlite_apply_in_session() { return 0; }
__attribute__((used)) uintptr_t zeppelinlite_forget_remote_state() { return 0; }
__attribute__((used)) uintptr_t zeppelinlite_stop_in_session() { return 0; }
